### ISSUE TITLE
Breaks PlainTasks plugin

### ISSUE THREAD

**Issue by Appius** [unlight/sublime-import-helper#40]
Somehow, installing this plugin breaks [PlainTasks plugin](https://github.com/aziz/PlainTasks).

When I try to create a new TODO item (by hot key, `ctrl+enter` for windows) in my `.todo` file, nothing happens and I get the following error in the console:
```
raceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 199, in create_text_commands
    cmds.append(class_(view))
  File "C:\Users\...\AppData\Roaming\Sublime Text 3\Packages\ImportHelper\do_insert_import.py", line 15, in __init__
    self.project_settings = project_data.get('import_helper') or {}
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 199, in create_text_commands
    cmds.append(class_(view))
  File "C:\Users\...\AppData\Roaming\Sublime Text 3\Packages\ImportHelper\do_insert_import.py", line 15, in __init__
    self.project_settings = project_data.get('import_helper') or {}
```
No commands are working while `ImportHelper` is installed next to it.
It's pretty sad for me, since I like to use both plugins on daily basis.

**Comment by jessecstewart** [comment]
I saw this error too. Can reproduce by simply creating a new window in Sublime. It seems to be related to having an empty/absent Sublime project. Maybe `do_insert_import.py:15` needs a null check?

**Comment by jessecstewart** [comment]
This issue may be fixed by https://github.com/unlight/sublime-import-helper/pull/41.  @Appius can you confirm?

**Comment by Appius** [comment]
Yes, it's working! Thank you very much! @jessecstewart
