### ISSUE TITLE
Cannot find node because NVM?

### ISSUE THREAD

**Issue by matutter** [unlight/sublime-import-helper#55]
Just after installing with package control this exception pops up and import-helper doesn't work.

```
Import Helper
Traceback (most recent call last):
  File "/home/mcutter/.config/sublime-text-3/Packages/ImportHelper/utils.py", line 39, in run_command
    (err, out) = exec([NODE_BIN, RUN_PATH, command, json])
  File "/home/mcutter/.config/sublime-text-3/Packages/ImportHelper/utils.py", line 62, in exec
    proc = subprocess.Popen(cmd, cwd=PACKAGE_PATH, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'node'
```

For clarity, 

```
mcutter@xps-13:~$ echo $PATH
/home/mcutter/.nvm/versions/node/v8.9.4/bin:/home/mcutter/bin:/home/mcutter/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
mcutter@xps-13:~$ which node
/home/mcutter/.nvm/versions/node/v8.9.4/bin/node
```

**Comment by unlight** [comment]
People were complaining at the beginning, but later, after some improvement, seems this error was resolved.

Did you try to specify `node_bin` explicitly?
https://github.com/unlight/sublime-import-helper#node_bin

**Comment by matutter** [comment]
@unlight Thanks! This fixes the issue.
