### ISSUE TITLE
Could not check for imports

### ISSUE THREAD

**Issue by rhizene** [unlight/sublime-import-helper#84]
> edit: I was on Node v 8.17.0

I am using Sublime Text v3.2.2 build 3211 on Linux Mint

The following appears when I try to update source modules / opening up a sublime project:

```
Import Helper
/home/ndimalanta/.config/sublime-text-3/Packages/ImportHelper/backend_run.js:8245
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
I tried removing  the Optional catch binding, but ended up with the ff:

```
/home/ndimalanta/.config/sublime-text-3/Packages/ImportHelper/backend_run.js:10809
	for await (const chunk of stdin) {
	    ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by unlight** [comment]
It's likely that you have old version of nodejs, please, update to v12 or v14

**Comment by rhizene** [comment]
@unlight thanks! I wasn't able to reply immediately but yes, node v12 resolved it for me

edit: before switching to  I was on Node 8.17.0.
